[project]
authors = ["Ryan Avery <ryanbarryavery@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "dask-odc"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
xarray = ">=2024.10.0,<2025"
rioxarray = ">=0.17.0,<0.18"
ray-all = ">=2.38.0,<3"
dask = ">=2024.10.0,<2025"
pystac-client = ">=0.8.5,<0.9"
jupyterlab = ">=4.3.0,<5"
matplotlib = ">=3.9.2,<4"
libgdal-arrow-parquet = ">=3.9.3,<4"
geopandas = ">=1.0.1,<2"
shapely = ">=2.0.6,<3"
seaborn = ">=0.13.2,<0.14"
xbatcher = ">=0.4.0,<0.5"
folium = ">=0.18.0,<0.19"
botocore = ">=1.35.54,<2"
ipywidgets = ">=8.1.5,<9"
odc-geo = ">=0.4.8,<0.5"
odc-stac = ">=0.3.10,<0.4"
python-duckdb = ">=1.1.3,<2"
tabulate = ">=0.9.0,<0.10"
python = "3.11.*"
lonboard = ">=0.10.3,<0.11"
gdal = ">=3.9.3,<4"

[pypi-dependencies]
stacrs = ">=0.2.2, <0.3"
